### PR TITLE
Tiny Changes & A Missing Paragraph Added

### PR DESCRIPTION
**Pull request by Ayx03**

### CODE REVIEW

**Review by kang8 — APPROVED** [review]

**Review by Ayx03 — COMMENTED** [review]
原文：If you still didn't find anything, post your question on the one site where it's most on-topic. Use the formatting tools, especially for code, and add tags that are related to the substance of your question (particularly the name of the programming language, operating system, or library you're having trouble with). If a commenter asks you for more information, edit your main post to include it. If any answer is helpful, click the up arrow to upvote it; if an answer gives a solution to your problem, click the check under the voting arrows to accept it as correct.


我不知道为什么这段从来没有被包含在译文中，但我认为它很重要。

**Comment by liijunwei** [comment]
我试着翻译一下，然后提个PR

**Comment by Ayx03** [comment]
@liijunwei I already included that in this pr🤣
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/pull/149/commits/adbc3a016ceffd326276547e54c80e7602af762f

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/pull/149/commits/cc4c241a18770e88dc1b30df5280cffef7252390

**Comment by liijunwei** [comment]
没注意到😅 关了PR

**Comment by Ayx03** [comment]
@ryanhanwu please review these changes

**Comment by ryanhanwu** [comment]
Awesome thanks!!

**Pull request merged**
